title: Jerry Peng
description: Mechanical Engineering Portfolio
theme: minima

email: jp2011pa@gmail.com
github_username: peng-jerry
linkedin_username: your-linkedin

header_pages:
  - resume.md
  - projects.md
  - about.md
