title: Jerry Peng
description: Mechanical Engineering Portfolio
theme: minima

email: jp2011pa@gmail.com
github_username: peng-jerry
   social_links:
     - title: Minima Theme repository at GitHub
       icon: github
       url: "https://github.com/jekyll/minima"

header_pages:
  - resume.md
  - projects.md
  - about.md
