title: Jerry Peng
description: Mechanical Engineering Portfolio
theme: minima

email: jp2011pa@gmail.com
github_username: peng_jerry
linkedin_username: <a href="https://www.linkedin.com/in/jerry-peng-706711231">LinkedIn</a>

header_pages:
  - resume.md
  - projects.md
  - about.md
