title: Jerry Peng
description: Mechanical Engineering Portfolio
theme: minima

email: jp2011pa@gmail.com
github_username: peng_jerry
linkedin_username: https://www.linkedin.com/in/jerry-peng-706711231

header_pages:
  - projects.md
  - about.md
  - resume.md
