title: Jerry Peng
description: Mechanical Engineering Portfolio
theme: minima

email: jp2011pa@gmail.com
github_username: peng-jerry
linkedin:
  - title: LinkedIn Profile
    icon: linkedin
    url: "https://www.linkedin.com/in/jerry-peng-706711231"

header_pages:
  - resume.md
  - projects.md
  - about.md
